Added method addNewCurrency() in MoneyBox
Jakobnr1/MoneyServiceGruppArbete pull request #78
Opened 2021-04-21 15:13 UTC by LindbergsKarl

2021-04-21 15:16 UTC, WazzUppP approved these changes
Ser okej ut.

2021-04-21 21:51 UTC, Jakobnr1 commented on src/MoneyServiceAPP/MoneyServiceAPP.java
> +									if(theSite.getCurrencyMap().get(currencyChoice).getTotalValue() >= Config.getMIN_AMMOUNT()){
Inte helt säker men vill man inte kolla med Optinal Double om man hur mycket valuta vi har?

2021-04-21 21:52 UTC, Jakobnr1 approved these changes
Check comment too, not sure

2021-04-21 22:30 UTC, PeterAngell requested changes
check comments in code check if changes nessecary and then ask for 2nd review

2021-04-21 22:30 UTC, PeterAngell commented on src/MoneyServiceAPP/MoneyServiceAPP.java
> +									if(theSite.getCurrencyMap().get(currencyChoice).getTotalValue() >= Config.getMIN_AMMOUNT()){
här kollar dom bara om värdet på den possitionen e mindre eller lika med Config.getMIN_AMOUNT(), kan hända att det hade varit bra att kalla på optional medtoden här istället för att skriva om samma sak i main. main bör ju använda metoder som redan finns så man slipper random null/ nullpointerexceptions

2021-04-22 08:16 UTC, LindbergsKarl commented on src/MoneyServiceAPP/MoneyServiceAPP.java
> +									if(theSite.getCurrencyMap().get(currencyChoice).getTotalValue() >= Config.getMIN_AMMOUNT()){
Det testas på rad 152 om valutan finns. Om  den gör det går den till rad 156. Alltså kommer man aldrig få det problemet.
Som Peter skriver så kollar vi bara om det finns mins MIN_AMOUNT

2021-04-22 22:41 UTC, merged

2021-04-22 22:42 UTC, PeterAngell commented
merged and deleted branch